# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
datas="datas"
whis="whis" # whisperの略

[files]
ignore-hidden = false
extend-exclude = [".git", "*.svg", "pnpm-lock.yaml"]
