name: "Setup environment"
description: |
  依存関係のインストールなどを行う。

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - name: Setup pnpm
      shell: bash
      run: pnpm install
